export const EXPENSE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SKIPPED: 'SKIPPED',
} as const;

export const OCR_JOB_STATUS = {
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export const EXPENSE_CATEGORY = {
  TRAVEL: 'TRAVEL',
  FOOD: 'FOOD',
  ACCOMMODATION: 'ACCOMMODATION',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER',
} as const;
